telegram_token: "6159895118:AAGuRfladv6Gm4NH--w9lvCdfmnxfLw0gck"
openai_api_key: "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"
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
